name = "api-emaction"
main = "src/worker.js"
compatibility_date = "2023-07-25"
usage_model = "bundled"
env = { }

[[d1_databases]]
binding = "d1" # i.e. available in your Worker on env.DB
database_name = "emaction"
database_id = "4e9a0917-50fd-4b86-9eb1-f4ba242ec748"

[triggers]
crons = [ ]
